### ISSUE TITLE
integral counts in 10s and 100s cause issues in the 2-digit benford graph

### ISSUE THREAD

**Issue by chrisdonlan** [milcent/benford_py#44]
So, if I push numbers with distributions in the 1's and 10's (nothing really less than 100), then the two digit benford registers the `1.0, 2.0, 3.0` etc. as instances of the 1-0, 2-0, (and so on) digit pattern. 

So, the bottom line issue is that for integral distributions involving some samples which are less than 10, the 2-digit benford will fail, and will yield a graph that can be a major false alarm. 

The function used was:

```
benford.first_digits
```

**Comment by milcent** [comment]
Please confirm:
- You´re using the `first_digits` for the **Fitrt-Two-Digits** (10, 11, 12, 13..., 99) test (param `digs`=2); and
- Yor sample has mostly numbers less than 100.
If so, probably your dataset is better analyzed only by the Firt(One)Digit test (param `digs`=1), since the records do not span through many orders of magnitude (which is one of the characteristics of a nice Benford set).
In fact, in the preparation of the set for the analysis, the First-Two-Digits test discards numbers less than 10, as do the First-Three-Digits with numbers less than 100, for obvious reasons.
You could also tweak the parameter `decimals`, that multiplies all the records by the given value (defalut=2 for currency), though I think it would not be very handy in this case.
Let me know if I got it right and if I could help.
Cheers,
Milcent
