### ISSUE TITLE
No such file or directory: '/wrkdirs/usr/ports/math/py-benford_py/work-py37/benford_py-0.3.2/README-pypi.md'

### ISSUE THREAD

**Issue by yurivict** [milcent/benford_py#48]
The build of the tarball 0.3.2 from the PyPI page fails:
```
===>  Configuring for py37-benford_py-0.3.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 6, in <module>
    with open(path.join(this_directory, 'README-pypi.md'), encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/wrkdirs/usr/ports/math/py-benford_py/work-py37/benford_py-0.3.2/README-pypi.md'
*** Error code 1
```

**Comment by milcent** [comment]
That is weird...
I have checked and it is really not buiding the dist with this file, that I use with slight modifications from the README to better show in Pypi, since it is markdown.
Could you install using pip?
From PyPI: `python -m pip install benford_py`
or directly from the github repo: `python -m pip install git+https://github.com/milcent/benford_py.git@master`
